# Generated by Django 3.1.13 on 2021-09-07 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('pass', 'Password'), ('key', 'Private Key')], default='key', max_length=10)),
                ('ssh_key', models.TextField(max_length=1000)),
                ('ssh_key_passphrase', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('last_used', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ssh_host', models.CharField(max_length=100)),
                ('ssh_port', models.PositiveIntegerField()),
                ('ssh_user', models.CharField(max_length=50)),
                ('client_version', models.CharField(blank=True, help_text='Leave blank for client install', max_length=20, null=True)),
                ('hetzner_id', models.IntegerField(unique=True)),
                ('ssh_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.authdata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
